// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://nyuekmrmclncdfwkzfsu.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im55dWVrbXJtY2xuY2Rmd2t6ZnN1Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDcwNDAzMTMsImV4cCI6MjA2MjYxNjMxM30.rL3Ez5lDQkShhExJuhe3SDy9sr9DhLFaGbIT7tZABic";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);